#!/bin/sh

export CC="/build/musl/linux-x86_64/bin/musl-clang"
export CXX="${CC}++"

exec cmake -S runtimes -B /tmp/llvm-build -DCMAKE_INSTALL_PREFIX="/build/musl/linux-x86_64" \
    -DCMAKE_INSTALL_LIBDIR=lib64 -DLLVM_LIBDIR_SUFFIX=64 \
    -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
    -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" \
    -DLIBCXXABI_USE_LLVM_UNWINDER=ON \
    -DLIBUNWIND_ENABLE_STATIC=ON -DLIBUNWIND_ENABLE_SHARED=OFF \
    -DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON -DLIBCXXABI_USE_COMPILER_RT=ON \
    -DLIBCXXABI_ENABLE_STATIC=ON -DLIBCXXABI_ENABLE_SHARED=OFF \
    -DLIBCXX_ENABLE_STATIC=ON -DLIBCXX_ENABLE_SHARED=OFF -DLIBCXX_HAS_MUSL_LIBC=ON \
    -DCMAKE_BUILD_TYPE=Release
